name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  date_picker_timeline: ^1.2.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.16
  flutter_timezone: ^3.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  sqflite: ^2.4.1
  timezone: ^0.10.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - pics/
